//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace Dovecote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pigeon
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string RingNO { get; set; }
        public Nullable<System.DateTime> Hatched { get; set; }
        public Nullable<long> Yearbook { get; set; }
        public byte[] Image { get; set; }
        public string Comment { get; set; }
        public string Dovecote { get; set; }
        public string EyeColor { get; set; }
        public string Color { get; set; }
        public string Race { get; set; }
        public string Line { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Father { get; set; }
        public Nullable<long> Mother { get; set; }

		public override string ToString() {
			return $"{RingNO} {Name}";
		}

	    public Pigeon GetFather() {
		    var pigeon = (List<Pigeon>)Provider.GetList<Pigeon>(typeof(Pigeon));
		    return pigeon.FirstOrDefault(p => p.Id == Father);
	    }

		public Pigeon GetMother() {
			var pigeon = (List<Pigeon>)Provider.GetList<Pigeon>(typeof(Pigeon));
			return pigeon.FirstOrDefault(p => p.Id == Mother);
		}

		
	}
}
